version: '3'

services:
    ###> doctrine/doctrine-bundle ###
    database:
        image: mariadb:${DATABASE_SERVER_VERSION}
        volumes:
            - "symfony_blog_database_data:/var/lib/mysql:rw"
###< doctrine/doctrine-bundle ###

volumes:
    ###> doctrine/doctrine-bundle ###
    symfony_blog_database_data: ###< doctrine/doctrine-bundle ###
